<form id="form-employee" onsubmit="false">
    <div class="row">
        <div class="col-md-6">
            <div class="mb-3">
                <label for="name" class="form-label">{{ __('Name')}}</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="{{ __('Example') }} : Jhone Doe" autocomplete="off">
                <input type="hidden" name="id" id="id" class="form-control">
                <input type="hidden" name="user_id" id="user_id" class="form-control">
            </div>
        </div>
        <div class="col-md-6">
            <div class="mb-3">
                <label for="gender" class="form-label">{{ __('Gender')}}</label>
                <select name="gender" id="gender" class="form-control">
                    <option value="">{{ __('Please Select') }}</option>
                    @foreach (config('enum.gender') as $item)
                        <option value="{{ $item }}">{{ Str::ucfirst($item) }}</option>
                    @endforeach
                </select>
            </div>
        </div>
        <div class="col-md-6">
            <div class="mb-3">
                <label for="address" class="form-label">{{ __('Address')}}</label>
                <input type="text" class="form-control" id="address" name="address" placeholder="{{ __('Example') }} : Jl.Diponegoro IV" autocomplete="off">
            </div>
        </div>
        <div class="col-md-6">
            <div class="mb-3">
                <label for="phone" class="form-label">{{ __('Phone')}}</label>
                <input type="text" class="form-control" id="phone" name="phone" placeholder="{{ __('Example') }} : 082244xxxxxx" autocomplete="off">
            </div>
        </div>
        <div class="col-md-6">
            <div class="mb-3">
                <label for="position" class="form-label">{{ __('Position')}}</label>
                <input type="text" class="form-control" id="position" name="position" placeholder="{{ __('Example') }} : HRD" autocomplete="off">
            </div>
        </div>
        <div class="col-md-6">
            <div class="mb-3">
                <label for="department_id" class="form-label">{{ __('Department')}}</label>
                <select name="department_id" id="department_id" class="form-control">
                    <option value="">{{ __('Please Select') }}</option>
                    @foreach ($department as $d)
                        <option value="{{ $d->id }}">{{ $d->name }}</option>
                    @endforeach
                </select>
            </div>
        </div>
        <div class="col-md-6">
            <div class="mb-3">
                <label for="email" class="form-label">{{ __('Email')}}</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="{{ __('Example') }} : example@gmail.com" autocomplete="off">
                <input type="hidden" class="form-control" id="username" name="username" readonly autocomplete="off">
            </div>
        </div>
        <div class="col-md-6">
            <div class="mb-3">
                <label for="role" class="form-label">{{ __('Role')}}</label>
                <select name="role" id="role" class="form-control">
                    <option value="">{{ __("Please Select") }}</option>
                    @foreach (config("enum.role") as $role)
                        <option value="{{ $role }}">{{ Str::ucfirst($role) }}</option>
                    @endforeach
                </select>
            </div>
        </div>
        <div class="col-md-12">
            <div class="mb-3">
                <label for="shift_id" class="form-label">{{ __('Shift')}}</label>
                <select name="shift_id" id="shift_id" class="form-control">
                    <option value="0">{{ __("Please Select") }}</option>
                    @foreach ($shifts as $shift)
                        <option value="{{ $shift->id }}">{{ Str::ucfirst($shift->name) }}</option>
                    @endforeach
                </select>
            </div>
        </div>
        <div class="col-md-6">
           <small class="text-danger">{{ __("*Note: User password will be generated by default 12345678") }}</small>
        </div>
    </div>
</form>

@push('js')
    <script>
        $("input[name=phone]").on("input",function(){
            var value = $(this).val();
            $("input[name=username]").val(value);
        })
    </script>
@endpush

